Added stochastic to requirements
After installing via `python setup.py install`, I recieved the following error:

``python
ModuleNotFoundError: No module named 'stochastic'
```

Adding the `stochastic` module to the required packages solved this problem